import Head from "next/head";
import Image from "next/image";
import ActionItems from "../components/Home/ActionItems";
import mapboxgl from "!mapbox-gl";
import { useEffect } from "react";
import Map from "../components/Home/Map";
import { auth } from "../firebase";
import { useRouter } from "next/router";

mapboxgl.accessToken =
  "pk.eyJ1IjoicmVoYW50b3NpZiIsImEiOiJjbGEycjloZzkwajg2M3Bxdm1rM2diNHlqIn0.SrZTiiNtWGhlAVHKqLQIiA";

export default function Home() {
  const router = useRouter();
  const user = auth.currentUser;
  useEffect(() => {
    !user && router.push("/login");
  }, []);

  return (
    <>
      <Head>
        <title>Uber</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map />
      <ActionItems />
    </>
  );
}
